### ISSUE TITLE
Porting of Linux

### ISSUE THREAD

**Issue by nitrofurano** [paladin-t/b8#1]
it’s indeed relevant! :)

**Comment by paladin-t** [comment]
Yep, I won't miss it, there are plans for new features, portings and standalone player exporting, and more... But I must accomplish them one by one, as working as an independent on this. I'll write down the roadmap for future later.

**Comment by paladin-t** [comment]
Now available on [Linux](http://store.steampowered.com/app/767240/), since v1.2.3.
