### ISSUE TITLE
Awesome tool.Will support more language?

### ISSUE THREAD

**Issue by Humhah** [paladin-t/b8#10]
I saw this tool in steam,like it so much.
Will you add more language-support in future?
Wish more people like it.(●'ω'●)丿❤

**Comment by paladin-t** [comment]
Python is on a [mindstrom list](https://github.com/paladin-t/b8/projects/2), which would be major versions later even if determined.

The main factor is, there are risks to introduce new languages until it could run across platforms.

**Comment by Humhah** [comment]
Feel sad.It seems like practicing my English is necessary.
Good luck.(●'ω'●)丿❤

**Comment by paladin-t** [comment]
Thanks, I can use Chinese natively, and daily English.

中文英文都行，不过建议英文，不然大家看上去就像两个人在打乒乓球却不能参与了。

**Comment by paladin-t** [comment]
;D
