### ISSUE TITLE
Crash when using modulo for floating point

### ISSUE THREAD

**Issue by JasonNumberThirteen** [paladin-t/b8#27]
I accidentally typed float value for MOD operation and after first frame of execution, it freezes completely the software and vanishes (crash). If modulo for floats aren't supported it should be notification from compiler to change into integer value. Using this in if-conditional:

`if t MOD 0.5 > 0.25 then` : where 't' is a counter of elapsed time with delta time addition,

crashes "BASIC8" immediately.

**Comment by paladin-t** [comment]
Thanks for the bug report.

Fixed.
