### ISSUE TITLE
False conjunction of two "is type" true booleans

### ISSUE THREAD

**Issue by JasonNumberThirteen** [paladin-t/b8#28]
When i use `[X] is type ("dict")` separating from `[Y] is type ("string")` both of them gives me true, but when I try to join them with the "AND", it gives me false even, when types match.

`[X] is type ("dict") and [Y] is type ("string")` gives me false, even when I insert dictionary and string in order.

**Comment by paladin-t** [comment]
The `is` operator has the same precedence with `and` and `or`. Consider using `([X] is type ("dict")) and ([Y] is type ("string"))`.

**Comment by JasonNumberThirteen** [comment]
Got it.
