### ISSUE TITLE
Index out of bounds error in "rnd" method

### ISSUE THREAD

**Issue by JasonNumberThirteen** [paladin-t/b8#32]
I noticed that "rnd" method throws an error about "index out of bounds" when minimum and maximum range are the same. That was so confusing, I analyzed my code many times searching the reason, but I didn't knew this could be caused by single value in range. I don't know how can I call it, is it a bug, an issue or just a mistake, but for sure it shouldn't throw an error for this.

**Comment by paladin-t** [comment]
It's a feature, the max specifier should be greater than the min.
