### ISSUE TITLE
2 Music channels for me are not enough :-) 3 or 4?

### ISSUE THREAD

**Issue by ToddlD** [paladin-t/b8#4]

**Comment by paladin-t** [comment]
Hi Toddl,

The 2 music channels are using SoundFont synther, similar as MIDI. And the 4 SFX channels are waveforms, in each can use all among sine/square/triangle/sawtooth/noise.

I'm considering to make a "disk" as audio tool, with which can also use SFX channels for long sequence as waveform based music. That should be enough.

The other problem that I'd prefer not to make more audio channels available is, it may consume a lot CPU time and power especially on mobile platforms, so there won't be more before I could test that with mobile.
